create table aircraft (id bigint not null auto_increment, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table aircraft_schedules (aircraft_id bigint not null, schedules_id bigint not null) engine=InnoDB;
create table airline (id bigint not null auto_increment, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table airline_schedules (airline_id bigint not null, schedules_id bigint not null) engine=InnoDB;
create table airport (country_id integer, latitude float(53) not null, longitude float(53) not null, id bigint not null auto_increment, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table airport_schedules (airport_id bigint not null, schedules_id bigint not null) engine=InnoDB;
create table country (id integer not null auto_increment, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table country_airports (country_id integer not null, airports_id bigint not null) engine=InnoDB;
create table schedule (duration decimal(21,0), aircraft_id bigint, airline_id bigint, arriaval_airport_id bigint, arrival_date_time datetime(6), departure_airport_id bigint, departure_date_time datetime(6), id bigint not null auto_increment, flight_number varchar(255), primary key (id)) engine=InnoDB;
alter table aircraft_schedules add constraint UKgm4ihl5yil1bgig07rp7bpq1m unique (schedules_id);
alter table airline_schedules add constraint UKg1pxy019rnc2xnnwi90f35ig8 unique (schedules_id);
alter table airport_schedules add constraint UKnm4lfky1mnxx4ejhwptevghkb unique (schedules_id);
alter table country_airports add constraint UKqu4r2mwpsr0l4om98bxtk3o0m unique (airports_id);
alter table aircraft_schedules add constraint FKr70xtc35pfofdsg1nowvwljp2 foreign key (schedules_id) references schedule (id);
alter table aircraft_schedules add constraint FKt8y5e4xee3kd6fclrcunyubik foreign key (aircraft_id) references aircraft (id);
alter table airline_schedules add constraint FKj3emok1cb3vx0o33ri7lb660s foreign key (schedules_id) references schedule (id);
alter table airline_schedules add constraint FKpdr65a67pm2wedlx73v0l79ag foreign key (airline_id) references airline (id);
alter table airport add constraint FKb3pphrsecshbmqr9end680veg foreign key (country_id) references country (id);
alter table airport_schedules add constraint FK4kc0y3jcfv2o1inslkxvwxxj7 foreign key (schedules_id) references schedule (id);
alter table airport_schedules add constraint FK6elb3kahd95e15aw6lcnjtbs2 foreign key (airport_id) references airport (id);
alter table country_airports add constraint FKjjo812bq9x2b4o74pvf0wlvdm foreign key (airports_id) references airport (id);
alter table country_airports add constraint FK1j4rbhiy5mid6jophl9iyjwfo foreign key (country_id) references country (id);
alter table schedule add constraint FKm23tnlatjmbxrr5l262ga3mkb foreign key (aircraft_id) references aircraft (id);
alter table schedule add constraint FKskc8fp5bypp42fyed86xr7e2n foreign key (airline_id) references airline (id);
alter table schedule add constraint FKrnere1b08uxep7mnkrt84n9rc foreign key (arriaval_airport_id) references airport (id);
alter table schedule add constraint FKgcs9isiaiip107cemy5jjuld3 foreign key (departure_airport_id) references airport (id);
