alter table aircraft_schedules drop foreign key FKr70xtc35pfofdsg1nowvwljp2;
alter table aircraft_schedules drop foreign key FKt8y5e4xee3kd6fclrcunyubik;
alter table airline_schedules drop foreign key FKj3emok1cb3vx0o33ri7lb660s;
alter table airline_schedules drop foreign key FKpdr65a67pm2wedlx73v0l79ag;
alter table airport drop foreign key FKb3pphrsecshbmqr9end680veg;
alter table airport_schedules drop foreign key FK4kc0y3jcfv2o1inslkxvwxxj7;
alter table airport_schedules drop foreign key FK6elb3kahd95e15aw6lcnjtbs2;
alter table country_airports drop foreign key FKjjo812bq9x2b4o74pvf0wlvdm;
alter table country_airports drop foreign key FK1j4rbhiy5mid6jophl9iyjwfo;
alter table schedule drop foreign key FKm23tnlatjmbxrr5l262ga3mkb;
alter table schedule drop foreign key FKskc8fp5bypp42fyed86xr7e2n;
alter table schedule drop foreign key FK4c8rdl0biudwvsiobe8vd4i5q;
alter table schedule drop foreign key FKgcs9isiaiip107cemy5jjuld3;
drop table if exists aircraft;
drop table if exists aircraft_schedules;
drop table if exists airline;
drop table if exists airline_schedules;
drop table if exists airport;
drop table if exists airport_schedules;
drop table if exists country;
drop table if exists country_airports;
drop table if exists schedule;
